export default {
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: 'hsl(var(--primary))',
        'primary-foreground': 'hsl(var(--primary-foreground))',
        secondary: 'hsl(var(--secondary))',
        'secondary-foreground': 'hsl(var(--secondary-foreground))',
        muted: 'hsl(var(--muted))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        accent: 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart1: 'hsl(var(--chart-1))',
        chart2: 'hsl(var(--chart-2))' /*  */,
        chart3: 'hsl(var(--chart-3))',
        chart4: 'hsl(var(--chart-4))',
        chart5: 'hsl(var(--chart-5))',
        sidebar: 'hsl(var(--sidebar))',
        'sidebar-foreground': 'hsl(var(--sidebar-foreground))',
        'sidebar-primary': 'hsl(var(--sidebar-primary))',
        'sidebar-primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
        'sidebar-accent': 'hsl(var(--sidebar-accent))',
        'sidebar-accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
        'sidebar-border': 'hsl(var(--sidebar-border))',
        'sidebar-ring': 'hsl(var(--sidebar-ring))',
        /* --ruijie自定义主题色-- */
        /* --品牌色-- */
        'primary-hover': 'hsl(var(--primary-hover))',
        'primary-active': 'hsl(var(--primary-active))',
        'primary-disabled': 'hsl(var(--primary-disabled))',
        'primary-special': 'hsl(var(--primary-special))',
        'primary-light': 'hsl(var(--primary-light))',
        /* --成功色-- */
        success: 'hsl(var(--success))',
        'success-hover': 'hsl(var(--success-hover))',
        'success-active': 'hsl(var(--success-active))',
        'success-disabled': 'hsl(var(--success-disabled))',
        'success-special': 'hsl(var(--success-special))',
        'success-light': 'hsl(var(--success-light))',
        /* --告警色-- */
        danger: 'hsl(var(--danger))',
        'danger-hover': 'hsl(var(--danger-hover))',
        'danger-active': 'hsl(var(--danger-active))',
        'danger-disabled': 'hsl(var(--danger-disabled))',
        'danger-special': 'hsl(var(--danger-special))',
        'danger-light': 'hsl(var(--danger-light))',
        /* --异常色-- */
        abnormal: 'hsl(var(--abnormal))',
        'abnormal-hover': 'hsl(var(--abnormal-hover))',
        'abnormal-active': 'hsl(var(--abnormal-active))',
        'abnormal-disabled': 'hsl(var(--abnormal-disabled))',
        'abnormal-special': 'hsl(var(--abnormal-special))',
        'abnormal-light': 'hsl(var(--abnormal-light))',
        /* --警示色-- */
        warning: 'hsl(var(--warning))',
        'warning-hover': 'hsl(var(--warning-hover))',
        'warning-active': 'hsl(var(--warning-active))',
        'warning-disabled': 'hsl(var(--warning-disabled))',
        'warning-special': 'hsl(var(--warning-special))',
        'warning-light': 'hsl(var(--warning-light))',
        /* --文字/图标-- */
        'secondary-information': 'hsl(var(--secondary-information))',
        'disabled': 'hsl(var(--disabled))',
        'text': 'hsl(var(--text))',
        /* --线/描边-- */
        'border-hover': 'hsl(var(--border-hover))',
        'border-special': 'hsl(var(--border-special))',
        'border-disabled': 'hsl(var(--border-disabled))',
        'border-line': 'hsl(var(--border-line))',
        'border-split': 'hsl(var(--border-split))',
        'border-dark': 'hsl(var(--border-dark))',
        /* --交互填充色-- */
        fill: 'hsl(var(--fill))',
        'fill-emphasize': 'hsl(var(--fill-emphasize))',
        'fill-light-hover-bg': 'hsl(var(--fill-light-hover-bg))',
        'fill-dark-hover-active-disabled': 'hsl(var(--fill-dark-hover-active-disabled))',
        'fill-dark': 'hsl(var(--fill-dark))',
        /* --数据-- */
        'data-1': 'hsl(var(--data-1))',
        'data-2': 'hsl(var(--data-2))',
        'data-3': 'hsl(var(--data-3))',
        'data-4': 'hsl(var(--data-4))',
        'data-5': 'hsl(var(--data-5))',
        'data-6': 'hsl(var(--data-6))',
        'data-7': 'hsl(var(--data-7))',
        'data-8': 'hsl(var(--data-8))',
        'data-9': 'hsl(var(--data-9))',
      },
    },
  },
  darkMode: 'class',
}
